# Generated by Django 5.0.7 on 2024-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_location_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
    ]
