# Generated by Django 5.0.7 on 2024-07-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_spot_is_available_spot_available_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='capacity',
        ),
    ]
