# Generated by Django 5.0.7 on 2024-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_remove_location_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='total_capacity',
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='spot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
