# Generated by Django 5.0.7 on 2024-07-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_spot_available_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_number',
            field=models.CharField(default='DEFAULT_ID', max_length=20),
        ),
    ]
