# Generated by Django 5.0.7 on 2024-07-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_reservation_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='estimated_time',
        ),
    ]
