# Generated by Django 5.0.7 on 2024-07-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_reservation_date_reserved_reservation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reserved',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_number',
            field=models.CharField(default='DEFAULT_ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.spot'),
        ),
    ]
